# Generated by Django 3.2.5 on 2021-08-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SPORTS', 'SPORTS'), ('INVENTIONS', 'INVENTIONS'), ('MUSIC', 'MUSIC'), ('STEM', 'STEM'), ('POLITICS', 'POLITICS'), ('LITERATURE', 'LITERATURE'), ('ART', 'ART'), ('FASHION', 'FASHION'), ('EMPIRES', 'EMPIRES')], max_length=50)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('coord_v', models.FloatField()),
                ('coord_h', models.FloatField()),
                ('is_liked', models.BooleanField(default=False)),
                ('has_viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
