# Generated by Django 3.2.5 on 2021-08-13 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Category',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=100)),
        #     ],
        # ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('coord_v', models.FloatField()),
                ('coord_h', models.FloatField()),
                ('is_liked', models.BooleanField(default=False)),
                ('has_viewed', models.BooleanField(default=False)),
                # ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.category')),
            ],
        ),
    ]
