# Generated by Django 3.2.5 on 2021-08-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
